export const ACTION_TYPE = {
  READING_TO_KANA: 1,
  KANA_TO_READING: 2,
  HIRAGANA_TO_KATAKANA: 3,
  KATAKANA_TO_HIRAGANA: 4,
  QUERY_KANA_TO_READING: 5,
  QUERY_READING_TO_KANA: 6,
  QUERY_HIRAGANA_TO_KATAKANA: 7,
  QUERY_KATAKANA_TO_HIRAGANA: 8
};

export const ACTION_TYPE_LABEL_ZHCN = {
  [ACTION_TYPE.READING_TO_KANA]: "练习：读音 -> 假名",
  [ACTION_TYPE.KANA_TO_READING]: "练习：假名 -> 读音",
  [ACTION_TYPE.HIRAGANA_TO_KATAKANA]: "练习：平假名 -> 片假名",
  [ACTION_TYPE.KATAKANA_TO_HIRAGANA]: "练习：片假名 -> 平假名",
  [ACTION_TYPE.QUERY_KANA_TO_READING]: "查平假名/片假名对应的读音",
  [ACTION_TYPE.QUERY_READING_TO_KANA]: "查读音对应的假名",
  [ACTION_TYPE.QUERY_HIRAGANA_TO_KATAKANA]: "查平假名对应的片假名",
  [ACTION_TYPE.QUERY_KATAKANA_TO_HIRAGANA]: "查片假名对应的平假名"
};
